name: Cross Platform Tests

on:
  # Run for all PRs
  pull_request:
  # Run again once merged into development branch
  push:
    branches:
      - development

jobs:
  run-ios-tests:
    timeout-minutes: 30
    runs-on: macos-latest
    steps:
      - name: "Update XCode tools"
        run: |
          sudo xcode-select -v
          sudo xcode-select -s /Applications/Xcode_12.5.1.app
          sudo xcode-select -v
          xcodebuild -version
      - name: "Checkout Cross Platform Tests"
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.APPLE_SDK_PAT }} #medium-term solution, this needs to be an MParticle/non-personal PAT
          submodules: "true"
          repository: mParticle/crossplatform-sdk-tests
          fetch-depth: 1
      - name: "Checkout internal"
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          path: .sdks/apple
      - name: "Install JDK 11"
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - name: "Install Cocoapods"
        run: sudo gem install cocoapods; sudo gem install cocoapods-generate
      - name: Run Tests
        run: ./gradlew runIos
      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ios-test-results
          path: Users/runner/Library/Developer/Xcode/DerivedData